### ISSUE TITLE
Incorrect SV48_Vaddr bitfield

### ISSUE THREAD

**Issue by dylux** [riscv/sail-riscv#101]
Current implementation of SV48_Vaddr in riscv_vmem_common.sail is an exact copy of SV39_Vaddr, which is incorrect since the VPNi field should have a range of 47 .. 12.
https://github.com/rems-project/sail-riscv/blob/cf099be2a1aff1f326dc855875d5732607e28752/model/riscv_vmem_common.sail#L193-L196

**Comment by martinberger** [comment]
We reviewed it and the fix looks fine, we will merge it in soon.
