### ISSUE TITLE
Please move riscv_iris.sail to a branch?

### ISSUE THREAD

**Issue by nwf** [riscv/sail-riscv#119]
It clutters grep results while trying to work with the rest of the model (and, at least at a glance, looks like it could perhaps be mostly generated in the same concatenating way as the rest of the model?  I haven't checked to see if its duplicate definitions have significantly diverged).

**Comment by martinberger** [comment]
An alternative would be to move the IRIS stuff to a separate directory?

**Comment by Mjiig** [comment]
It should probably just be deleted. It was checked in while I was using it for some experiments but those haven't panned out or been worked on in almost a year, and to the best of my knowledge there are no other users.

**Comment by martinberger** [comment]
@Mjiig  Thanks. I think @rmn30 checked in `riscv_iris.sail`, so it would be good to hear from him. Who else could be using it?

**Comment by rmn30** [comment]
I think it is redundant and should be deleted. From memory I was trying to help someone by creating a stripped down version of the model as an experiment.

**Comment by martinberger** [comment]
Deleted and issue closed. Thanks everybody @ronorton  @Mjiig @nwf
