### ISSUE TITLE
Directions to build and support RV32D

### ISSUE THREAD

**Issue by shatyahariharan** [riscv/sail-riscv#120]
Help me with the steps to build and support for RV32D

**Comment by abukharmeh** [comment]
Also do you know what is the value of fcsr ?

**Comment by jrtc27** [comment]
The fact the disassembly shows `illegal 3523281619` rather than `fcvt.d.w ft5, sp` means it wasn't decoded successfully, it's not getting as far as looking at fcsr.FRM or mstatus.FS. I can't see this being anything other than using an old version of the model.

**Comment by shatyahariharan** [comment]
> The model is claiming that FCVT.D.W is an illegal instruction. Are you compiling the latest version from GitHub ?

yes, I am using the latest version
