### ISSUE TITLE
Writing misa should suppress entire write if C=0 illegal

### ISSUE THREAD

**Issue by scottj97** [riscv/sail-riscv#123]
The privileged spec says:

> Writing misa may increase IALIGN, e.g., by disabling the “C” extension. If an instruction that would write misa increases IALIGN, and the subsequent instruction’s address is not IALIGN-bit aligned, the write to misa is suppressed, leaving misa unchanged.

[This code](https://github.com/riscv/sail-riscv/blob/4508059032ecfdb986a5673108b02900d2c4ccfd/model/riscv_sys_regs.sail#L157-L168) does not behave this way: it will suppress an unsupported write to the C bit, but still allow changes to the F & D bits.

If C cannot be disabled, all changes to misa must be suppressed.

**Comment by allenjbaum** [comment]
Definitely a bug
