### ISSUE TITLE
CSIM Build System

### ISSUE THREAD

**Issue by abukharmeh** [riscv/sail-riscv#155]
Hi, 

At the moment, the generated C definition of the simulator gets written to a single C file before being compiled. 
I wonder how realistic is it to transpile the model into many C files (trying to preserve the boundaries of the modules), and then compile these files.

I think this would help with debugging, and could perhaps help speed up recompilation of the model?
@jrtc27  Any ideas if this is possible as things stands? 

Ibrahim.

**Comment by scottj97** [comment]
It could speed up even a clean compile (not just incremental) if you use `make -j` to compile many C files in parallel.

**Comment by martinberger** [comment]
@abukharmeh This is more a Sail issue than RISCV model. I don't think the current Sail compiler gives you separate compilation. Sail doesn't really have a module system.

**Comment by abukharmeh** [comment]
I think perhaps somebody should try to come up with clear boundaries for each SAIL file in the model, @Alasdair  any thoughts from the general Sail perspective?

**Comment by martinberger** [comment]
@abukharmeh What do you mean by _"clear boundaries"_ here?

**Comment by Timmmm** [comment]
As @martinberger said this would require changes to the Sail compiler, so I'll close this here - feel free to reopen on [the Sail compiler repo](https://github.com/rems-project/sail) but I wouldn't hold your breath!
