### ISSUE TITLE
Error when building the model

### ISSUE THREAD

**Issue by haitianzhishang** [riscv/sail-riscv#176]
<img width="1005" alt="error" src="https://user-images.githubusercontent.com/38684938/185056207-7f0060cc-8c0d-442c-87fa-66e81c68fb3e.png">
After installing the sail by follow install.md from sail repo, ran make to build risc-v model and this error came. 
I'm really not sure about the reason for this error and hope for some directions. Thanks a lot

**Comment by bacam** [comment]
It looks like the Makefile expects the GNU version of sed and your system has a BSD one.  Could you try the changes in #177?  I think that should work but I don't have a BSD-style system set up for building sail-riscv at the moment.

**Comment by haitianzhishang** [comment]
> It looks like the Makefile expects the GNU version of sed and your system has a BSD one. Could you try the changes in #177? I think that should work but I don't have a BSD-style system set up for building sail-riscv at the moment.

error fixed. Thanks a lot!
