### ISSUE TITLE
Question about isa extension

### ISSUE THREAD

**Issue by haitianzhishang** [riscv/sail-riscv#180]
I would like to try to add some instructions based this RISC-V model. But I don't know how to debug it, I add some print information but don't know how to run it , what I can do is just running the "make check" to correct syntax errors. 
Is there some guidelines for debugging or testing? Really hope for it and thanks a lot

**Comment by martinberger** [comment]
By syntax errors, you mean errors in the *Sail* syntax? If so, the Sail compiler should flag those, no?

**Comment by haitianzhishang** [comment]
>

**Comment by haitianzhishang** [comment]
> By syntax errors, you mean errors in the _Sail_ syntax? If so, the Sail compiler should flag those, no?

For example, I add a new instruction in this model. How could I test this new instruction using Sail?

**Comment by martinberger** [comment]
Given that it's a new instruction, you'd probably have to create your own tests, or, provide a second implementation, e.g. in Spike or QEMU and run them against your updated Sail model.
