### ISSUE TITLE
No CHANGELOG.md file

### ISSUE THREAD

**Issue by allenjbaum** [riscv/sail-riscv#188]
We need a CHANGELOG file with a version number so that we can audit and debug test reports

**Comment by jrtc27** [comment]
Context? The changelog is called "read git log"...

**Comment by jrtc27** [comment]
Though from your _description_ you don't want a changelog, you want a version number, which is a duplicate of #109?

**Comment by allenjbaum** [comment]
Ah, yes, thanks, I couldn't a version number, so this is just a duplicate.
In our other repos, it's a line in the changelog, but a --version command is superior to have to parse that.
