### ISSUE TITLE
Copy/paste/modify error for xperm4 implementation (from xperm8)

### ISSUE THREAD

**Issue by ssecatchseagate** [riscv/sail-riscv#202]
This code appears to be copy and modified from xperm8. The bus ripping of [i+3..i] appears to be correctly modified, but the offset calculation of 8*index was not modifed to 4*index.     
result[i+3..i] = if 8*index < sizeof(xlen)
                     then rs1_val[8*index+3..8*index]
                     else zeros()
                     
Note that there is a bounds check issue in the specific of missing the -1 for the end as reported in this issue:
         https://github.com/riscv/riscv-crypto/issues/202 
The bounds in the SAIL model already appears to be correct

**Comment by jrtc27** [comment]
Duplicates #171 #186
