### ISSUE TITLE
Extracting values from monads

### ISSUE THREAD

**Issue by felipelisboa-ml** [riscv/sail-riscv#226]
Hi,

Is there a way to extract values from the monad type defined in `/prover_snapshots/coq/lib/Prompt_monad.v` ? I.e. the inverse of function of "returnm" ?

Reason is I'm trying to prove the correctness of a pure computation (using a Coq DSL) against the instruction semantics in sail_riscv. 

Thanks.

**Comment by bacam** [comment]
Yes, you can pattern match on the monad type; `returnm` is really just the `Done` constructor.

**Comment by felipelisboa-ml** [comment]
Thanks, worked just fine.
