### ISSUE TITLE
Error when making C/OCaml emulators after pulling new commits

### ISSUE THREAD

**Issue by XinlaiWan** [riscv/sail-riscv#231]
There is an error when making emulators in the master branch now. I'm not sure if there are problems in my Sail environment or other issues. Could someone help identify the issue?

```
Syntax error:
[model/prelude.sail]:111:10-10
111 |val not = pure {coq: "negb", _: "not"} : forall ('p : Bool). bool('p) -> bool(not('p))
    |          ^
    | current token: pure
make: *** [Makefile:202: generated_definitions/ocaml/RV64/riscv.ml] Error 1
```
```
Syntax error:
[model/prelude.sail]:111:10-10
111 |val not = pure {coq: "negb", _: "not"} : forall ('p : Bool). bool('p) -> bool(not('p))
    |          ^
    | current token: pure
make: *** [Makefile:236: generated_definitions/c/riscv_model_RV64.c] Error 1
```

**Comment by jrtc27** [comment]
The GitHub Actions build from 5 days ago built fine. What version of Sail are you using?

**Comment by jrtc27** [comment]
Probably you have an older version; 0.15 is required to support the pure keyword there.

**Comment by XinlaiWan** [comment]
Thank you! I was using Sail 0.14. No error occurs when I upgrade to Sail 0.15.
