### ISSUE TITLE
Overloading error while doing concatenation!

### ISSUE THREAD

**Issue by mustafa7755** [riscv/sail-riscv#271]
- I'm facing a issue while doing concatenation of a register bits, it gives an overloading error.
```
Type error:
model/riscv_sys_regs.sail:238.26-62:
238 |  let m : bits(32) = EXTZ(v[7 .. 6] @ v[5 .. 4] @ 0b000 @ v[0]);
    |                          ^----------------------------------^
    | No overloading for append, tried:
    | * bitvector_concat
    |    No overloading for append, tried:
    |    * bitvector_concat
    |       No overloading for append, tried:
    |       * bitvector_concat
    |          Could not unify bitvector('m, dec) and bit
    |       * vector_concat
    |          Could not unify vector('n, dec, 'a) and bitvector(3, dec)
    |    * vector_concat
    |       Could not unify vector('n, dec, 'a) and bitvector(((5 - 4) + 1), dec)
    | * vector_concat
    |    Could not unify vector('n, dec, 'a) and bitvector(((7 - 6) + 1), dec)

```
- For now, i have found a workaround for this, by doing this via a mask:
```
let m : bits(32) = v & EXTZ(0xF1);
```
- By second method, i can't make it a generic one, i.e., base it on XLEN bits. First approach would make this a generic one but not sure what's the issue with the first approach.

**Comment by Alasdair** [comment]
You can also do `[v[0]]`. At some point I would like to unify bit and `bits(1)` like they are in ASL.

**Comment by mustafa7755** [comment]
Thanks, both solutions work!

And how about this? It has 62-8 reserved bits(i.e., zero) but not the last one(63rd bit)
![image](https://github.com/riscv/sail-riscv/assets/92720160/038e0972-3433-4742-997a-07c2e2dbd47c)

I'm doing it like this(Shouldn't EXTZ extends zero's till 62nd bit? Is there any better way to do this?):
```
Mk_Menvcfg_ent([v[63]] @ EXTZ(v[7 .. 6] @ v[5 .. 4] @ 0b000 @ [v[0]]));
```
But, following overloading error get generated.
```
    | No overloading for append, tried:
    | * bitvector_concat
    |    Cannot solve implicit 'm in EXTZ(bitvector_concat(subrange_bits(v, 7, 6), bitvector_concat(subrange_bits(v, 5, 4), bitvector_concat(0b000, [bitvector_access(v, 0)]))))
    | * vector_concat
    |    Could not unify vector('n, dec, 'a) and bitvector(1, dec)

```

**Comment by rmn30** [comment]
In this case it looks like Sail isn't able to work out the length of the vector to return from `EXTZ`. You could use the version that explicitly specifies the length i.e. `EXTZ(63, ...)` or add a type annotation e.g. `EXTZ(...) : bits(63)`.

**Comment by mustafa7755** [comment]
Thanks @rmn30, this worked out for me. Closing this issue now.
