### ISSUE TITLE
Setting F=0 and D=1 should result in both F and D being cleared

### ISSUE THREAD

**Issue by ahadali-10x** [riscv/sail-riscv#300]
The privileged spec says:
>If an ISA feature x depends on an ISA feature y, then attempting to enable feature x but disable
feature y results in both features being disabled. For example, setting “F”=0 and “D”=1 results
in both “F” and “D” being cleared.

[This code](https://github.com/riscv/sail-riscv/blob/861bd6f65593013381c905d7a54e538e5382bf31/model/riscv_sys_regs.sail#L167-L172) does not behave this way: It will leave F & D alone instead of clearing both of them. So it could end up with e.g. F=1 D=0.

**Comment by billmcspadden-riscv** [comment]
@ahadali-10x ,  the PR has been merged.   Would you please close this issue?
