### ISSUE TITLE
No  `riscv_sim_RV64` created in `c_emulator/` dir. after running `ARCH=RV64 make`

### ISSUE THREAD

**Issue by quswarabid** [riscv/sail-riscv#333]
I have been trying to setup sail-riscv as a reference module to riscof using [these steps](https://riscof.readthedocs.io/en/latest/installation.html#test-riscof:~:text=%24%20sudo%20apt%2Dget%20install%20opam,execute%20them%20from%20command%20line.):

```
$ sudo apt-get install opam  build-essential libgmp-dev z3 pkg-config zlib1g-dev
$ opam init -y --disable-sandboxing
$ opam switch create ocaml-base-compiler.4.06.1
$ opam install sail -y
$ eval $(opam config env)
$ git clone https://github.com/riscv/sail-riscv.git
$ cd sail-riscv
$ make
$ ARCH=RV32 make
$ ARCH=RV64 make
$ ln -s sail-riscv/c_emulator/riscv_sim_RV64 /usr/bin/riscv_sim_RV64
$ ln -s sail-riscv/c_emulator/riscv_sim_RV32 /usr/bin/riscv_sim_RV32

This will create a C simulator in c_emulator/riscv_sim_RV64 and c_emulator/riscv_sim_RV32. You will not need to add these paths in your $PATH or an alias to it to execute them from command line.
```

But following all the steps I don't get a `riscv_sim_RV64` in `c_emulator/` Is there any known issue regarding this?

**Comment by jrtc27** [comment]
CI builds it fine. Maybe you have an old version of Sail?

**Comment by henrybear327** [comment]
> CI builds it fine. Maybe you have an old version of Sail?

@jrtc27 I was trying to build from scratch (on M1 using docker), and here are some commits that I have tried 
- ok 3fca4c87b98ebac2c1ecb174e22b4f57c3b1d4ee, 861bd6f65593013381c905d7a54e538e5382bf31,  6c7cb9bdbac76cb61512b48be0cb3aeb5c42e80d, e2e942c1e56ceea17a6a732a88391cc9b1276d0c
- failed 4c77f62622c199f14e0bd6cdc6a6c427fe31b09e -> `The following expression is unmatched: (undefined, [||])`
- ok 532714a6c71b47a91176eb90fef3b3b049c52fce
- failed 51a6c967fb320c2d47a3630b1f392e54eb69c3d7, c04cf29c2215ff614a83ac483b9545a995adca65, c90cf2e6eff5fa4ef7b93cc2020166dea7453fc6, 69af65cf41220a12dd4a62308c7dff537157f757

Toolchain used was:
  ∗ ocaml.4.13.1
  ∗ install conf-findutils     1          [required by lem]
  ∗ install ocamlfind          1.9.6      [required by linksem, lem, ott]
  ∗ install seq                base       [required by yojson]
  ∗ install ocamlbuild         0.14.2     [required by lem, linksem]
  ∗ install dune               3.11.1     [required by sail]
  ∗ install conf-gmp           4          [required by libsail]
  ∗ install conf-pkg-config    3          [required by conf-zlib]
  ∗ install num                1.4        [required by lem]
  ∗ install base-bytes         base
  ∗ install stdlib-shims       0.3.0      [required by ocamlgraph]
  ∗ install sail_manifest      0.16       [required by sail]
  ∗ install result             1.[5](https://github.com/riscv/sail-riscv/actions/runs/6648481351/job/18065547856#step:6:6)        [required by linenoise]
  ∗ install pprint             20230830   [required by libsail]
  ∗ install pp                 1.2.0      [required by dune-private-libs]
  ∗ install ordering           3.11.1     [required by dyn, stdune]
  ∗ install menhirSdk          20230[6](https://github.com/riscv/sail-riscv/actions/runs/6648481351/job/18065547856#step:6:7)0[8](https://github.com/riscv/sail-riscv/actions/runs/6648481351/job/18065547856#step:6:9)   [required by menhir]
  ∗ install menhirLib          20230608   [required by menhir]
  ∗ install csexp              1.5.2      [required by dune-private-libs]
  ∗ install cppo               1.6.[9](https://github.com/riscv/sail-riscv/actions/runs/6648481351/job/18065547856#step:6:10)      [required by yojson]
  ∗ install base64             3.5.1
  ∗ install zarith             1.13       [required by lem]
  ∗ install conf-zlib          1          [required by libsail]
  ∗ install omd                1.3.2
  ∗ install ocamlgraph         2.1.0      [required by ott]
  ∗ install linenoise          1.4.0      [required by sail]
  ∗ install dyn                3.11.1     [required by dune-private-libs]
  ∗ install menhir             20230608   [required by libsail]
  ∗ install yojson             2.1.1      [required by libsail]
  ∗ install lem                2022-12-[10](https://github.com/riscv/sail-riscv/actions/runs/6648481351/job/18065547856#step:6:11) [required by libsail]
  ∗ install ott                0.33       [required by libsail]
  ∗ install stdune             3.[11](https://github.com/riscv/sail-riscv/actions/runs/6648481351/job/18065547856#step:6:12).1     [required by dune-private-libs]
  ∗ install linksem            0.8        [required by libsail]
  ∗ install dune-private-libs  3.11.1     [required by dune-site]
  ∗ install dune-site          3.11.1     [required by libsail]
  ∗ install libsail            0.[16](https://github.com/riscv/sail-riscv/actions/runs/6648481351/job/18065547856#step:6:17)       [required by sail]
  ∗ install sail_smt_backend   0.16
  ∗ install sail_output        0.16
  ∗ install sail_ocaml_backend 0.16
  ∗ install sail_lem_backend   0.16
  ∗ install sail_latex_backend 0.16
  ∗ install sail_doc_backend   0.16
  ∗ install sail_coq_backend   0.16
  ∗ install sail_c_backend     0.16
  ∗ install sail               0.16

**Comment by Alasdair** [comment]
```
make: *** [Makefile:257: generated_definitions/c/riscv_model_RV64.c] Killed
```
Maybe it's running out of memory in the container and being OOM killed? I'm working on a new release of Sail with some significant memory usage improvements. It's not on opam yet, but you could give it a try?
