### ISSUE TITLE
How to access sail's memory?

### ISSUE THREAD

**Issue by animesh211** [riscv/sail-riscv#339]
Hi.
While trying to access a memory like 'f0000000' in the setup for atomics, I am seeing Exceptions being taken from sail model.
Seeing exceptions like these-

within_phys_mem: 0xF0000000 not within phys-mem:
plat_rom_base: 0x00001000
plat_rom_size: 0x00001000
plat_ram_base: 0x80000000
plat_ram_size: 0x04000000
trapping from M to M to handle store/amo-access-fault
handling exc#0x07 at priv M with tval 0xF0000000
CSR mstatus <- 0x00001800

How can I access this memory region?

**Comment by rmn30** [comment]
Looks like the address you are trying to access is outside the RAM defined for the model? From the output you give `plat_ram_base + plat_ram_size = 0xc0000000`. Looks like these values are currently [hardcoded](https://github.com/riscv/sail-riscv/blob/69af65cf41220a12dd4a62308c7dff537157f757/c_emulator/riscv_platform_impl.c#L19-L20) so you will either have to edit them and compile your own simulator or use a different address. There should probably be a way to configure this at runtime.
