### ISSUE TITLE
Warning (that looks serious) during 'make csim'

### ISSUE THREAD

**Issue by rsnikhil** [riscv/sail-riscv#341]
During compiling the model with `make csim` on commit 46750eed, I see the following warning:

    c_emulator/riscv_sim.c:1050:59: warning: format specifies type 'char *' but the argument has type 'FILE *' (aka 'struct __sFILE *') [-Wformat]
        fprintf(stderr, "Cannot create trace log '%s': %s\n", trace_log,
                                                  ~~          ^~~~~~~~~
    1 warning generated.

which seems serious (mistaking a `FILE *` for a `char *`)

**Comment by jrtc27** [comment]
#331

Another instance of PRs being neglected by those who are supposed to merge them
