### ISSUE TITLE
Looking for help/suggestion to locate source of a type error

### ISSUE THREAD

**Issue by ved-rivos** [riscv/sail-riscv#368]
Whats a good way to identify the cause for this error?

```
The following expression is unmatched: FVV_VFWREDOSUM

Type error:
No type declaration found for _s8698#
make: *** [Makefile:262: generated_definitions/c/riscv_model_RV64.c] Error 1

```

**Comment by ved-rivos** [comment]
I am developing an extension in my local checkout. I have narrowed it down to one file (a new file I added), which if exclude from make, makes the error go away. I will try to narrow it further by adding stuff into that file little by little.

**Comment by Alasdair** [comment]
If your version of Sail is < 0.17.1, I think an `opam update && opam ugrade sail`, might just fix it.

**Comment by arichardson** [comment]
> If your version of Sail is < 0.17.1, I think an `opam update && opam upgrade sail`, might just fix it.

Can we add a minimum version check? That would fix issues like this?

**Comment by Alasdair** [comment]
That might be a good idea, I made a draft PR to discuss that.
