### ISSUE TITLE
mstatus.mpp initialization and legalization?

### ISSUE THREAD

**Issue by nwf-msr** [riscv/sail-riscv#400]
When modeling a core that supports only M mode, we have noticed that the model does not enforce the WARL nature of `mstatus.MPP`:
1. `mstatus` legalisation (https://github.com/riscv/sail-riscv/blob/d5e89a71e3a84495c1b88a7749c25fd6b9da684b/model/riscv_sys_regs.sail#L297) does not check anything about `MPP`
2. system initialization (https://github.com/riscv/sail-riscv/blob/d5e89a71e3a84495c1b88a7749c25fd6b9da684b/model/riscv_sys_control.sail#L553) leaves `MPP` at the default `0b00`, which is only legal for cores supporting U mode.

As a consequence, if the first instruction the core runs is `mret`, we end up in an invalid state, attempting to execute an instruction in U mode.  We expect that these bits are always `0b11` for our core, yes?  I suspect that `legalize_mstatus` should use `haveSupMode` and `haveUsrMode` to gate `MPP` values, and, with less certainty, that initialization might either always set `MPP` to `0b11` or use those same utility functions to pick a value as close to `0b00` as the core would support?

**Comment by jrtc27** [comment]
https://github.com/riscv/sail-riscv/pull/397

**Comment by nwf-msr** [comment]
Argh!  I swear I searched for issues mentioning MPP.  Sorry for the noise.
