### ISSUE TITLE
is_CSR_defined has redundant privilege mode checks

### ISSUE THREAD

**Issue by Timmmm** [riscv/sail-riscv#402]
`is_CSR_defined` has a ton of `p == Machine` etc. checks that should be replaced by `true`, since the permission check is already handled in a generic way by this:

```
function check_CSR(csr : csreg, p : Privilege, isWrite : bool) -> bool =
    is_CSR_defined(csr, p)
  & check_CSR_access(csrAccess(csr), csrPriv(csr), p, isWrite)    <------------- this checks the privilege mode already
  & check_TVM_SATP(csr, p)
  & check_Counteren(csr, p)
  & check_seed_CSR(csr, p, isWrite)
```

**Comment by arichardson** [comment]
Agreed, removing those checks would make the function a lot simpler and also nicely separates "does the csr exist" from "is it currently accessible".
