### ISSUE TITLE
CSRs should use scattered functions

### ISSUE THREAD

**Issue by Timmmm** [riscv/sail-riscv#410]
The CSR code is a bit odd. For example `readCSR()` uses a `match`:

```
function readCSR csr : csreg -> xlenbits = {
  let res : xlenbits =
  match (csr, sizeof(xlen)) {
    /* machine mode */
    (0xF11,  _) => zero_extend(mvendorid),
...
```

but *also* a scattered function for extensions.

```
...

    _           => /* check extensions */
                   match ext_read_CSR(csr) {
                     Some(res) => res,
                     None()    => { print_bits("unhandled read to CSR ", csr);
                                    zero_extend(0x0) }
                   }
```

This is silly. It should just work like the scattered functions for instructions - everything uses scattered functions, and there's a `riscv_csrs_begin.sail` and `riscv_csrs_end.sail`, and you add new CSRs just by inserting extra files.

**Comment by defermelowie** [comment]
This is related to my [question](https://github.com/riscv/sail-riscv/issues/311) a while back. I agree that CSRs should use scattered functions but the question then is whether or not non-standard extensions should keep using the `ext_is_CSR_defined`, `ext_read_CSR` and `ext_write_CSR` hooks or use the scattered functions you propose here. The latter seems more consistent with the way instructions work.

**Comment by Timmmm** [comment]
Yes I agree there should be a single scattered function; no `ext_...`.
