### ISSUE TITLE
Remove `etc` directory

### ISSUE THREAD

**Issue by Timmmm** [riscv/sail-riscv#418]
It just has some stuff about adding copyright headers to files but they header has changed and it's short enough to easily do manually now.

**Comment by AbhinavMir** [comment]
Seems to just have `etc/headache_config` now which is referenced in a seemingly unused target inside Makefile. Should we get rid of it or do we need it? The scope of this automation seems small and can probably be refactored in some other way if needed.

**Comment by Timmmm** [comment]
Yeah I think remove it. Also I noticed there are a few files I missed in `handwritten_support` when updating the copyright header. But only 6, so we can probably just update them manually.
