### ISSUE TITLE
Sail model uses old asm mnmonics for vmandn and vmorn

### ISSUE THREAD

**Issue by mdhayter** [riscv/sail-riscv#421]
The mapping mmtype_mnemonic seems to be using the old vmandnot / vmornot rather than the new vmandn / vmorn

https://github.com/riscv/sail-riscv/blob/c287c34df944647fcfd1923e37f4d97466f264bd/model/riscv_insts_vext_mask.sail#L72C1-L73C1

See note in https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc section 15.1

Should be ok where aliases are used, but it is probably best to line up with the usage in riscv-opcodes/rv_v

**Comment by ShivangMishra** [comment]
@Timmmm I raised PR #465 for this issue. Does it look ok?

**Comment by ShivangMishra** [comment]
@Timmmm can we close this issue?

**Comment by Timmmm** [comment]
Yep
