### ISSUE TITLE
Spellings for misaligned store/AMO exception is wrong

### ISSUE THREAD

**Issue by Mudassir10X** [riscv/sail-riscv#430]
https://github.com/riscv/sail-riscv/blame/cb373efc372928c1205047c12ff12df20f890a4a/riscv_types.sail#L318

I noticed this a few months back as I am working specifically on misaligned support for sail-riscv, this **E_SAMO_Addr_Align** exception gives the **"misaliged-store/amo"** exception instead of **"misaligned-store/amo"**. I wanted to point this issue out even if it is not an issue in the working of the sail-model. But no one noticed this since 6 years when this was written here.

**Comment by Alasdair** [comment]
Made a PR to fix this
