### ISSUE TITLE
Is vector extension still in development?

### ISSUE THREAD

**Issue by sequencer** [riscv/sail-riscv#443]
I'm the architect of [T1](https://github.com/chipsalliance/t1), a standard RVV implementation in Chisel. We originally use spike a golden model for co-simulation. Recently we want to migrate to sail for a formal-based verification flow. Thanks to @XinlaiWan, It's delightful to see there is an on going work on the vector extension support for RISC-V. However I saw the vector branch is 5 months ago, and wonder if there is a plan to merge it?
cc @billmcspadden-riscv, @XinlaiWan

**Comment by Alasdair** [comment]
It's been merged

**Comment by sequencer** [comment]
Nice! I’ll try it. Thank you!
