### ISSUE TITLE
Many compilation warnings in OCaml emulator: ignored-partial-application

### ISSUE THREAD

**Issue by Kakadu** [riscv/sail-riscv#507]
The CI version builds OCaml emulator with a lot of warnings. The most severe of them is 
````
File "riscv.ml", line 12439, characters 4-48:
12439 |     Softfloat.f64_round_to_int (zrm, zv, zexact);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Warning 5 [ignored-partial-application]: this function application is partial,
maybe some arguments are missing.
````
The compiler says that this function is not really called, and extra argument(s) seems to be forgotten. This means that correctness of the emulator could be in danger. 

P.S. I couldn't find mentions about this neither here nor in https://github.com/rems-project/sail/issues . Maybe I should cross-post...

**Comment by Timmmm** [comment]
Yeah I noticed this too. The OCaml emulator doesn't actually support float currently anyway so it's probably not a big deal. This will change when the float implementation is moved from Berkeley softfloat to native Sail, which which case these functions will be deleted anyway.

**Comment by jordancarlin** [comment]
This can be closed now that the OCaml emulator is gone
