### ISSUE TITLE
Remove OCaml emulator

### ISSUE THREAD

**Issue by Timmmm** [riscv/sail-riscv#509]
Can we remove the OCaml emulator? I think this would have significant benefits:

* Less confusing for new users - they no longer need to choose between two very similar but different emulators.
* We no longer have to implement emulator features twice.
* Contributors don't need to learn OCaml.
* Shorter CI time.
* When we use the binary release of the Sail compiler, this will mean we can entirely drop OCaml as a dependency, even in CI.

**Comment by trdthg** [comment]
Discussions from the past: #138

**Comment by martinberger** [comment]
Another problem with the Ocaml emu is 

- Very slow!

**Comment by arichardson** [comment]
I've also found having to add the ocaml callbacks for every new features a bit annoying in the past (especially since I can't write ocaml and just copy-paste). So +1 from me.

**Comment by jordancarlin** [comment]
Is this something that we're planning to proceed with? I can look into it if so.

**Comment by Timmmm** [comment]
Yeah in the weekly meeting we basically agreed to do it and I said I would make a PR, but I've only ~30% completed it.

One thing we didn't discuss which is a unique OCaml backend feature is the thing where it can generate random instructions based on the `encdec` mapping, which I believe is used by TestRig. It doesn't depend on the emulator or OCaml callbacks but we might want to still keep the "generate OCaml code" Makefile targets which it presumably uses (I haven't checked yet).
