### ISSUE TITLE
Duplicate vector CSR code

### ISSUE THREAD

**Issue by Timmmm** [riscv/sail-riscv#548]
The code for reading/writing vector CSRs is duplicated [here](https://github.com/riscv/sail-riscv/blob/31f809346e1020d191b46d519ad6435e2428be39/model/riscv_insts_zicsr.sail#L66) and [here](https://github.com/riscv/sail-riscv/blob/31f809346e1020d191b46d519ad6435e2428be39/model/riscv_vext_control.sail#L18). The latter is not used because the former takes priority.

The code is not actually the same, so something is definitely not right.

**Comment by trdthg** [comment]
(One more point, The `ext_read_CSR` functions are also duplicated in the latter file
https://github.com/riscv/sail-riscv/blob/31f809346e1020d191b46d519ad6435e2428be39/model/riscv_vext_control.sail#L18-L24
