### ISSUE TITLE
Replace sizeof(xlen) with xlen

### ISSUE THREAD

**Issue by Timmmm** [riscv/sail-riscv#561]
Currently the model has a load of `sizeof(xlen)` everywhere because `xlen` is a type, not a variable:

```
type xlen       : Int = xlen_bytes * 8
```

You need `sizeof()` to convert the type into a variable. However Sail types and variables are in different namespaces, so you can have a type that is the same name as a variable, like this:

```
type xlen       : Int = xlen_bytes * 8
let xlen = sizeof(xlen)
```

The CHERI model uses this extensively - [see here for example](https://github.com/CTSRD-CHERI/sail-cheri-riscv/blob/c93d5eff4132fd52ddad32020cedae93573bfa29/src/cheri_prelude_128.sail#L64).

I think we should do the same for `xlen` in this model. It makes the code more readable and more like pseudo-code, and I can't see any downsides.

Any thoughts?

**Comment by rsnikhil** [comment]
I agree.  AFAIK type expressions and value expressions are completely disjoint, so there is no confusion about a name that happens to be in both namespaces.
