### ISSUE TITLE
Outdated Status.md file

### ISSUE THREAD

**Issue by jordancarlin** [riscv/sail-riscv#576]
The [docs/Status.md](https://github.com/riscv/sail-riscv/blob/master/doc/Status.md) file has fallen very far out of date. It is missing many of the extensions now included in the model and only includes a small subset of the supported configuration options. 

It should either be updated or removed. I'd be in favor of removing it since it clearly hasn't been missed, but could also see a case for wanting to keep it and ensure that it stays up to date going forward.

**Comment by trdthg** [comment]
How about moving it to the README? For example, [Spike](https://github.com/riscv-software-src/riscv-isa-sim#about) declares the extensions and version it currently supports in the README.

**Comment by jordancarlin** [comment]
Makes sense to me
