### ISSUE TITLE
mstatus[FS] not dirtied on writes to `fcsr` with Zfinx?

### ISSUE THREAD

**Issue by Timmmm** [riscv/sail-riscv#625]
From my reading of the code if you write to `fcsr` with Zfinx it will call this:

```
val write_fcsr : (bits(3), bits(5)) -> unit
function write_fcsr (frm, fflags) = {
  fcsr[FRM]    = frm;      /* Note: frm can be an illegal value, 101, 110, 111 */
  fcsr[FFLAGS] = fflags;
  dirty_fd_context_if_present();
}

...

function dirty_fd_context_if_present() -> unit = {
  assert(sys_enable_fdext() != sys_enable_zfinx());
  if sys_enable_fdext() then dirty_fd_context()
}
```

So it *won't* call `dirty_fd_context()`. I'm pretty sure that's incorrect.

**Comment by KotorinMinami** [comment]
As mentioned in unpriv spec Chapter 25:
>In the standard privileged architecture defined in Volume II, the mstatus field FS is hardwired to 0 if
>the Zfinx extension is implemented, and FS no longer affects the trapping behavior of floating-point
>instructions or fcsr accesses.
>
>The misa bits F, D, and Q are hardwired to 0 when the Zfinx extension is implemented

So I think this is the correct behavior for the spec definition.

**Comment by Timmmm** [comment]
Ahh good find!
