### ISSUE TITLE
sail-riscv Model May Enters Infinite Loop in RISC-V Arch Test PMP Cases

### ISSUE THREAD

**Issue by noionion** [riscv/sail-riscv#640]
The sail-riscv model seems to enter an infinite loop in the following pmp cases of riscv-arch-test. The specific sail configuration used is as follows: `--pmp-count=16 --pmp-grain=12`. I am not sure whether the issue lies with sail, my configuration, or the riscv-arch-test pmp cases themselves.

![image](https://github.com/user-attachments/assets/47800d2d-2313-4546-9607-24592e6346b8)
![image](https://github.com/user-attachments/assets/e75a4cb3-e831-4e44-b09f-1ab0923980c0)

(the DUT is our core ip)

**Comment by allenjbaum** [comment]
Specifically - this likely is a test issue. not a Sail issue.

**Comment by noionion** [comment]
Thank you for your reply! This issue will be closed.
